name: final_project_2023
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animate_do: ^3.0.2
  icon: ^2.2.1
  iconsax: ^0.0.8
  dark_light_button: ^0.0.2
  app_theme_mode: ^1.0.0
  google_fonts: ^4.0.1
  google_nav_bar: ^5.0.6
  animated_bottom_navigation_bar: ^1.1.0+1
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  form_field_validator: ^1.1.0
  form_validator: ^2.1.1
  google_maps_flutter: ^2.2.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.3.1
  location: ^4.4.0
  url_launcher: ^6.1.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

